---
# install tasks for ansible-role-kodi

- name: Install software-properties-common
  apt: pkg=software-properties-common state=installed update_cache=true

- name: Add kodi repository 
  apt_repository: repo='ppa:team-xbmc/ppa' state=present

- name: Install kodi repository 
  apt: pkg=kodi state=installed update_cache=true

- name: Create upstart script
  template: src=kodi.conf.j2 dest=/etc/init/kodi.conf owner={{ username }} group={{ username }} mode=0775

- name: Copy over Xwrapper config
  copy: src=Xwrapper.config dest=/etc/X11/Xwrapper.config owner=root group=root mode=644 

- name: Create autostart directory
  file: dest=/home/{{username}}/.config/autostart state=directory


  #- name: Create .kodi directory
  #file: path=/home/{{username}}/.kodi state=directory owner={{ username }} group={{ username }}

  #To create : tar -zcvf kodibackup.tar.gz .kodi
  #- name: Copy kodibackup.tar 
  #copy: src=kodibackup.tar.gz dest=/home/{{ username }}/kodibackup.tar.gz owner={{ username }} group={{ username }} 

  #- name:  Extract kodibackup tar
  #unarchive: src=/home/{{ username }}/kodibackup.tar.gz  dest=/home/{{ username }}/ copy=no owner={{ username }} group={{ username }}

- name: Copy startup file
  copy: src=kodi.desktop dest=/home/{{ username }}/.config/autostart/kodi.desktop owner={{ username }} group={{ username }} mode=664

  #- name: Copy Config Backup
  #copy: src=201603112141.zip dest=/home/{{ username }}/.kodi/201603112141.zip owner={{ username }} group={{ username }} mode=0664

  #- name: Copy Backup file to .kodi 
  #command: mv /home/{{ username }}/kodibackup.tar.gz /home/{{ username }}/.kodi/kodibackup.tar.zip
